language: node_js
node_js:
  - "12.11"

branches:
  only:
    - master

sudo: true

before_script:
  - npm i -g @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
    branch: master
