/**
 * Blog generator — build-time content pipeline.
 * Scans content/blog/*.md, validates, renders markdown with syntax highlighting,
 * and emits:
 *   - src/app/data/blog.generated.ts (the Angular data source)
 *   - public/sitemap.xml (regenerated with blog URLs)
 *   - public/feed.xml (RSS 2.0)
 *
 * Runs automatically via npm pre-hooks on start/build/build:ghpages.
 * Exit non-zero on any validation error — the failed build IS the content test.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';
import { createHighlighter } from 'shiki';

const CONTENT_DIR = 'content/blog';
const OUTPUT_TS = 'src/app/data/blog.generated.ts';
const SITE_URL = 'https://mohakchugh.is-a.dev';
const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*\.md$/;

// ── Shiki setup ──────────────────────────────────────────────────────────────
const highlighter = await createHighlighter({
  themes: ['github-dark-default'],
  langs: ['typescript', 'javascript', 'html', 'css', 'json', 'bash', 'python', 'java', 'markdown', 'yaml', 'sql'],
});

function highlightCode(code, lang) {
  try {
    return highlighter.codeToHtml(code, { lang: lang || 'text', theme: 'github-dark-default' });
  } catch {
    return `<pre><code>${escapeHtml(code)}</code></pre>`;
  }
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ── Marked config ────────────────────────────────────────────────────────────
marked.use({
  renderer: {
    code({ text, lang }) {
      return highlightCode(text, lang);
    },
  },
});

// ── Scan + parse ─────────────────────────────────────────────────────────────
if (!existsSync(CONTENT_DIR)) {
  mkdirSync(CONTENT_DIR, { recursive: true });
}

const files = readdirSync(CONTENT_DIR).filter((f) => f.endsWith('.md')).sort();
const errors = [];
const posts = [];

for (const file of files) {
  const filePath = join(CONTENT_DIR, file);

  // validate filename
  if (!SLUG_RE.test(file)) {
    errors.push(`${file}: filename must be kebab-case (${SLUG_RE})`);
    continue;
  }

  const slug = basename(file, '.md');
  const raw = readFileSync(filePath, 'utf-8');
  const { data: fm, content } = matter(raw);

  // validate frontmatter
  if (!fm.title || typeof fm.title !== 'string') {
    errors.push(`${file}: missing or invalid 'title' in frontmatter`);
    continue;
  }
  if (!fm.date || isNaN(Date.parse(fm.date))) {
    errors.push(`${file}: missing or invalid 'date' (must be ISO yyyy-mm-dd)`);
    continue;
  }
  if (fm.tags && !Array.isArray(fm.tags)) {
    errors.push(`${file}: 'tags' must be an array`);
    continue;
  }

  // skip drafts
  if (fm.draft) {
    console.log(`  [draft] skipping ${file}`);
    continue;
  }

  // render markdown
  const html = await marked.parse(content);

  // compute excerpt
  const plainText = content.replace(/[#*`\[\]()>_~|]/g, '').replace(/\n+/g, ' ').trim();
  const excerpt = fm.excerpt || plainText.slice(0, 160).replace(/\s\S*$/, '') + '…';

  // compute reading time
  const wordCount = plainText.split(/\s+/).length;
  const readingMinutes = Math.max(1, Math.ceil(wordCount / 200));

  // generate FAQ from ## headings (convert statement headings to questions)
  const headings = [...content.matchAll(/^## (.+)$/gm)].map((m) => m[1].trim());
  const faq = headings.slice(0, 5).map((h) => {
    const question = h.endsWith('?') ? h : `What is ${h.toLowerCase().replace(/^the /, '')}?`;
    // Extract the paragraph following this heading as the answer
    const headingIdx = content.indexOf(`## ${h}`);
    const afterHeading = content.slice(headingIdx + h.length + 4);
    const nextSection = afterHeading.indexOf('\n## ');
    const sectionText = (nextSection > 0 ? afterHeading.slice(0, nextSection) : afterHeading)
      .replace(/[#*`\[\]()>_~|]/g, '')
      .replace(/\n+/g, ' ')
      .trim();
    const answer = sectionText.slice(0, 200).replace(/\s\S*$/, '') + (sectionText.length > 200 ? '…' : '');
    return { question, answer };
  }).filter((f) => f.answer.length > 20);

  const date = new Date(fm.date).toISOString().slice(0, 10);

  posts.push({
    slug,
    title: fm.title,
    date,
    tags: fm.tags || [],
    excerpt,
    readingMinutes,
    html,
    faq,
  });
}

// ── Fail hard on errors ──────────────────────────────────────────────────────
if (errors.length > 0) {
  console.error('\n❌ Blog content validation failed:\n');
  errors.forEach((e) => console.error(`  • ${e}`));
  console.error('');
  process.exit(1);
}

// Sort date descending (newest first)
posts.sort((a, b) => b.date.localeCompare(a.date));

console.log(`✓ ${posts.length} blog post(s) processed`);

// ── Emit blog.generated.ts ───────────────────────────────────────────────────
const tsContent = `// GENERATED by scripts/generate-blog.mjs — do not edit manually.
// Source of truth: content/blog/*.md

import { BlogPost } from './portfolio.models';

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export const BLOG_MAP = new Map(BLOG_POSTS.map((p) => [p.slug, p]));
`;

writeFileSync(OUTPUT_TS, tsContent, 'utf-8');
console.log(`  → ${OUTPUT_TS}`);

// ── Emit sitemap.xml (core + projects + blog) ────────────────────────────────
// Read existing project slugs from the projects data
const projectSlugs = [];
try {
  const projData = readFileSync('src/app/data/projects.data.ts', 'utf-8');
  const slugMatches = projData.matchAll(/slug:\s*'([^']+)'/g);
  for (const m of slugMatches) projectSlugs.push(m[1]);
} catch { /* ignore if file missing */ }

// Topic hub keys for sitemap
const topicKeys = ['ml-gpu', 'systems', 'data', 'distributed', 'frontend'];

const sitemapUrls = [
  { loc: `${SITE_URL}/`, priority: '1.0' },
  { loc: `${SITE_URL}/projects`, priority: '0.9' },
  { loc: `${SITE_URL}/blog`, priority: '0.9' },
  { loc: `${SITE_URL}/cv`, priority: '0.8' },
  { loc: `${SITE_URL}/stats`, priority: '0.5' },
  { loc: `${SITE_URL}/contact`, priority: '0.7' },
  ...topicKeys.map((k) => ({ loc: `${SITE_URL}/topics/${k}`, priority: '0.8' })),
  ...projectSlugs.map((s) => ({ loc: `${SITE_URL}/projects/${s}`, priority: '0.6' })),
  ...posts.map((p) => ({ loc: `${SITE_URL}/blog/${p.slug}`, priority: '0.7' })),
];

const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapUrls.map((u) => `  <url><loc>${u.loc}</loc><priority>${u.priority}</priority></url>`).join('\n')}
</urlset>
`;
writeFileSync('public/sitemap.xml', sitemapXml, 'utf-8');
console.log(`  → public/sitemap.xml (${sitemapUrls.length} URLs)`);

// ── Emit feed.xml (RSS 2.0) ──────────────────────────────────────────────────
const rssItems = posts
  .map(
    (p) => `    <item>
      <title>${escapeHtml(p.title)}</title>
      <link>${SITE_URL}/blog/${p.slug}</link>
      <pubDate>${new Date(p.date).toUTCString()}</pubDate>
      <description>${escapeHtml(p.excerpt)}</description>
    </item>`,
  )
  .join('\n');

const feedXml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Mohak Chugh — Blog</title>
    <link>${SITE_URL}/blog</link>
    <description>Engineering notes by Mohak Chugh, SDE 2 at Amazon.</description>
    <language>en</language>
    <atom:link href="${SITE_URL}/feed.xml" rel="self" type="application/rss+xml"/>
${rssItems}
  </channel>
</rss>
`;
writeFileSync('public/feed.xml', feedXml, 'utf-8');
console.log(`  → public/feed.xml (${posts.length} items)`);

// Done
highlighter.dispose();
